name: Lint

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        run: corepack enable

      - name: Set node version to 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Ls
        run: ls -a

      - name: Setup
        run: npm i -g @antfu/ni

      - name: Install
        run: ni --frozen

      - name: Lint
        run: nr lint
